"""Is there an AI disclosure a *user* would actually see?

Kept separate from the Article 50 rule because the notice is usually not in the
Python file that calls the model — it lives in a template or a frontend
component. Checking only the calling module reports a missing disclosure on an
application that displays one, which is the worst kind of false positive:
confidently wrong about something the customer can see on their own screen.

The first version of this was far too broad and silenced the rule on every
repository in the corpus. It matched `CHANGELOG.md`, `docs/SECURITY.md`, a
langchain test fixture containing "AI Assistant", and tutorials using the phrase
"AI agent". Two corrections followed:

* **Documentation is not a disclosure.** A README saying the product uses
  artificial intelligence is not a notice delivered to a person at the moment
  they interact with the system. Markdown, changelogs and config files are out.
* **Product nouns are not notices.** "AI assistant" and "artificial
  intelligence" describe a thing; Article 50 is about *informing* someone. Only
  phrasings that address a user survive.
"""
from __future__ import annotations

import ast
import re

# Phrasings that inform a person they are dealing with a machine. Each one is
# something you would put in front of a user, not in a spec sheet.
PATTERNS = [
    re.compile(p, re.IGNORECASE) for p in (
        r"\bai[\s\-]generated\b",
        r"generated by (an?\s+)?ai\b",
        r"(you|users?) (are|'re|’re) (now )?(chatting|speaking|interacting|talking|communicating) with (an?\s+)?(ai|bot|chatbot|virtual|automated|machine)",
        r"\b(this|the) (is|response is|reply is|content is) (an?\s+)?(ai|bot|chatbot|automated|machine)[\s\-]?(generated|assistant|response)?\b",
        r"\bai\s+(can|may|might)\s+(make|produce)\b",         # "AI can make mistakes"
        r"\bnot (a )?(human|person)\b.{0,40}\bai\b",
        r"powered by (an?\s+)?ai\b",
        r"\bautomated (system|assistant|agent|response)\b",
        r"guardia:\s*disclosure",
    )
]

# Where a user-visible string can live at runtime. Markdown, text, JSON and
# YAML are deliberately absent — documentation and fixtures are not notices.
TEMPLATE_SUFFIXES = (
    ".html", ".htm", ".jinja", ".jinja2", ".j2", ".vue", ".svelte",
    ".js", ".jsx", ".ts", ".tsx", ".erb", ".hbs",
)


def has_disclosure(text: str) -> bool:
    return any(pattern.search(text) for pattern in PATTERNS)


def is_template(path: str) -> bool:
    return path.lower().endswith(TEMPLATE_SUFFIXES)


def _docstring_nodes(tree: ast.Module) -> set[int]:
    """Ids of Constant nodes that are docstrings, which are documentation."""
    ids: set[int] = set()
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        body = getattr(node, "body", None)
        if not body:
            continue
        first = body[0]
        if isinstance(first, ast.Expr) and isinstance(first.value, ast.Constant) \
                and isinstance(first.value.value, str):
            ids.add(id(first.value))
    return ids


def python_string_literals(tree: ast.Module) -> list[str]:
    """Every string literal except docstrings.

    A comment or a docstring saying "this is an AI" tells the reader of the code
    something; only a string can reach a user.
    """
    skip = _docstring_nodes(tree)
    return [
        node.value
        for node in ast.walk(tree)
        if isinstance(node, ast.Constant)
        and isinstance(node.value, str)
        and id(node) not in skip
    ]


def in_strings(strings: list[str]) -> bool:
    return any(has_disclosure(value) for value in strings)


def in_python_source(tree: ast.Module) -> bool:
    """A disclosure in a Python string literal — not a comment or docstring."""
    return in_strings(python_string_literals(tree))
