"""Add an AI disclosure to a handler's JSON response.

Article 50(1) requires that the person be *informed*. That means the notice has
to reach them, so the only fix we can verify from the syntax tree is one applied
to a dictionary literal the handler actually returns — the payload that will be
serialised and sent.

Anything else declines. A streaming response, a `return some_object`, a
`JSONResponse(...)` built elsewhere: all real, none safely patchable without
knowing what the client renders. Offering no fix is a normal outcome; the
finding still stands on its own.
"""
from __future__ import annotations

import ast
from typing import Optional

from ..models import SuggestedFix
from .objects import insert_entry

DISCLOSURE_KEY = "ai_disclosure"
DISCLOSURE_TEXT = "This response was generated by an AI system."

# Streamlit, Gradio and friends have no response object to patch — the script
# writes to the page directly, so the notice is written the same way. Four of
# the corpus findings were Streamlit chatbots with nowhere for a JSON field to
# go.
_UI_NOTICE_CALLS = {
    "streamlit": "st.caption",
    "gradio": "gr.Markdown",
    "chainlit": "cl.Message",
}


def build_ui_notice_fix(source: str, imports, call_line: int, call_end: int):
    """A visible notice for a script whose output is the page itself."""
    import re as _re

    from ..models import SuggestedFix

    framework = next((name for name in _UI_NOTICE_CALLS if name in imports), None)
    if framework is None:
        return None
    if framework != "streamlit":
        # Only Streamlit's one-liner is safe to place without knowing how the
        # interface is assembled; the others need their layout.
        return None

    lines = source.splitlines()
    if call_line < 1 or call_end > len(lines):
        return None

    span = lines[call_line - 1:call_end]
    indent = _re.match(r"\s*", span[0]).group(0)
    entry = f'{indent}st.caption("{DISCLOSURE_TEXT}")'

    return SuggestedFix(
        description=(
            "Show the disclosure on the page. Streamlit writes its interface as "
            "it runs, so the notice goes where the answer does — move it beside "
            "whatever renders the response if that reads better."
        ),
        start_line=call_line,
        end_line=call_end,
        replacement="\n".join([*span, entry]),
        confidence="medium",
    )


def _returned_dict(func: ast.AST) -> Optional[ast.Dict]:
    """The dict literal this function returns, if there is exactly one.

    Two different returned shapes mean two places to patch and a judgement about
    which is the user-facing one — so we decline rather than guess.
    """
    found: list[ast.Dict] = []
    for node in ast.walk(func):
        if isinstance(node, ast.Return) and isinstance(node.value, ast.Dict):
            found.append(node.value)
    return found[0] if len(found) == 1 else None


def _already_discloses(node: ast.Dict) -> bool:
    for key in node.keys:
        if isinstance(key, ast.Constant) and isinstance(key.value, str):
            if key.value.lower() in {DISCLOSURE_KEY, "disclosure", "ai_notice"}:
                return True
    return False


def build_disclosure_fix(source: str, func: ast.AST, file: str) -> Optional[SuggestedFix]:
    """A replacement for the returned dict literal, with the notice added."""
    target = _returned_dict(func)
    if target is None or _already_discloses(target):
        return None

    segment = ast.get_source_segment(source, target)
    if not segment:
        return None

    entry = f'"{DISCLOSURE_KEY}": "{DISCLOSURE_TEXT}"'
    rendered = insert_entry(
        source, target.lineno, getattr(target, "end_lineno", target.lineno) or target.lineno,
        segment, entry,
    )
    if rendered is None:
        return None

    start = target.lineno
    end = getattr(target, "end_lineno", start) or start

    return SuggestedFix(
        description=(
            "Add an AI disclosure to the response payload so the person "
            "receiving it is informed they are interacting with an AI system."
        ),
        start_line=start,
        end_line=end,
        replacement=rendered,
        # The transformation is exact, but whether this payload is what the
        # user actually sees is the author's call, not ours.
        confidence="medium",
    )
