"""Add an AI disclosure to a JavaScript or TypeScript JSON response.

Same change as the Python codemod, different shape: there the payload is a
returned dict, here it is the object handed to `Response.json({...})` or
`res.json({...})`. Anything else declines — a streamed response, a body built
elsewhere, two different response shapes in one handler.

Only the body is patched. A disclosure belongs where the user will see it, and
a JSON field is the closest thing to that a scanner can safely reach; whether
the client renders it is the author's call, which is why the fix carries medium
confidence and is never applied automatically.
"""
from __future__ import annotations

from typing import Optional

from .. import js
from ..models import SuggestedFix
from .objects import insert_entry

DISCLOSURE_KEY = "ai_disclosure"
DISCLOSURE_TEXT = "This response was generated by an AI system."

_EXISTING_KEYS = {DISCLOSURE_KEY, "disclosure", "aiNotice", "ai_notice", "aiDisclosure"}


def build_disclosure_fix(
    source: str,
    path: str,
    start_line: int,
    end_line: int,
) -> Optional[SuggestedFix]:
    """A patch for the response body of the handler spanning these lines."""
    candidates = js.json_response_objects(path, source, start_line, end_line)
    if len(candidates) != 1:
        # None means nothing patchable; more than one means choosing which
        # response the user actually sees, which is a guess.
        return None

    target = candidates[0]
    if any(key in _EXISTING_KEYS for key in target["keys"]):
        return None

    entry = f'{DISCLOSURE_KEY}: "{DISCLOSURE_TEXT}"'
    replacement = insert_entry(
        source, target["line"], target["end_line"], target["text"], entry,
    )
    if replacement is None:
        return None

    return SuggestedFix(
        description=(
            "Add an AI disclosure to the response body so the person receiving "
            "it is informed they are interacting with an AI system."
        ),
        start_line=target["line"],
        end_line=target["end_line"],
        replacement=replacement,
        confidence="medium",
    )
